# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SDK-Sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SDK-Sample

  pod 'SyneriseSDK', :git => 'https://github.com/Synerise/ios-sdk.git', :branch => 'v3.0.0'
end
